### ISSUE TITLE
Words from some languages getting past the filter

### ISSUE THREAD

**Issue by Bytedefined** [Gasegamer/super-profanity#1]
Languages such as: Russian and French seem to be getting past the filter, but languages such as Chinese and English seem to be working just fine.

**Comment by Bytedefined** [comment]
I looked into the code, and to me it seems like it only checks one language, which is your main language? Are you able to make it check **all** languages?

**Comment by Bytedefined** [comment]
accidentally closed lol

**Comment by Bytedefined** [comment]
There also seem to be false flags for words such as "grass"

**Comment by Gabriel-Ciriaco** [comment]
> Languages such as: Russian and French seem to be getting past the filter, but languages such as Chinese and English seem to be working just fine.

Hi,
    Firstly, thanks for the report, I will take a look at this issue with Russian and French, but if you want to have better precision on them, try setting them as the main language.

**Comment by Gabriel-Ciriaco** [comment]
> I looked into the code, and to me it seems like it only checks one language, which is your main language? Are you able to make it check **all** languages?

Your main language serves as a guarantee that the code will check for swears in a desired language. This is necessary, because the detection of the language (which is done by the TinyLD package) is not completely accurate, especially in very short sentences.

If you look again at the code, you will see that it uses the `detectAll` function of that package, which detects the different possibilities of the language in which the sentence was written. However, I will check if I used it properly to make sure it is using in all possible languages.

**Comment by Gabriel-Ciriaco** [comment]
> There also seem to be false flags for words such as "grass"

I'll take a look at that too and update `Read-ME` to show the `whitelist` and `blacklist` functions in addition to a brief explanation about `main language`.

Again, thanks for the report.

**Comment by Bytedefined** [comment]
Thanks

**Comment by Bytedefined** [comment]
any updates?

**Comment by Gabriel-Ciriaco** [comment]
> any updates?
> 

Currently no, sorry. I've been traveling for a few days and that's why I haven't been able to do anything for now.

**Comment by Gabriel-Ciriaco** [comment]
> any updates?

- Fixed the problem of some words being detected wrongly.
- Fixed the checker to detect and ignore whitelisted words.
- Updated the README to clarify some functionality.

Unfortunatelly, no success with the problem of bad detection in Russian and French. However, you can, for now, use the `changeMainLanguage`, `whiteListWord` and/or `blackListWord` functions to solve this problem.

**Comment by Gabriel-Ciriaco** [comment]
This issue was fixed in [Release 1.1.1](https://github.com/Gasegamer/super-profanity/releases/tag/1.1.1).
